# Generated by Django 4.2.16 on 2024-09-16 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_comment_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_on"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="update_on",
            new_name="updated_on",
        ),
    ]
